spring:
  application:
    name: auth-service
  profiles:
    active: local
  jpa:
    properties:
      query:
        in_clause_parameter_padding: true
        plan_cache_max_size: 1024
        plan_parameter_metadata_max_size: 64