oauth:
  apple:
    public-key-url: https://appleid.apple.com/auth/keys
  kakao:
    public-key-info: https://kauth.kakao.com/.well-known/jwks.json

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
